### ISSUE TITLE
Babel env target is not compatible with ie11 browser and uglify-js webpack plugin

### ISSUE THREAD

**Issue by vitaliymaz** [julien-f/js-json-rpc-protocol#29]
Currently babel env target is "node 4" which doesn't transpile es6 template literals to regular javascript string concatenation. As a result it breaks the application inside ie11 browser and also it breaks uglifying the production code with uglify-js plugin. 
As a workaround I process this library additionally with a webpack, but it looks not nice because only the one package from the node_modules requires such extra work.

## Expected Behavior
Strings inside /dist/ folder should be transpiled to es5 format.

## Current Behavior
ES6 template literals are present inside the build
```javascript
`method not found: ${method}`
```

## Possible Soultion
1. Use another target which includes all es5 plugins
2. Use "targets.uglify: true" option of babel preset-env to force babel transpile everything to es5

P.S. I'm not sure string templates are the only issue, maybe some another es6 features are not transpiled as well. Let's make decision on this and I'm ready to create PR then.

**Comment by julien-f** [comment]
I think these issues should be fixed at the bundler level instead, but, because of how small this package is and how easy it is to fix, I'm willing to make an exception.

I've added `uglify` to the list of targets, keep me posted if that's not enough.

**Comment by vitaliymaz** [comment]
Good job. Thank you very much.
