### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by huan** [julien-f/js-json-rpc-protocol#30]
Can we rewrite the project in TypeScript, so that we can get the typing support easily?

It will only require some minor changes to the code because we are already using ES6.

If so, I'll be happy to help, for example, send a Pull Request for that.

**Comment by julien-f** [comment]
Isn't it possible to simply add typedefs to the package?

**Comment by huan** [comment]
Yes, it's possible.

However, that would make us have to do the additional sync works between the JS and the TypeDefs, and also cannot be benefited from the TypeScript when we develop this package itself.

I'm trying to find a json-rpc package and after did the search work on the Google/NPM, I feel that `json-rpc-protocol` is great(`json-rpc-peer` too), except that we are leaking the TypeDefs.

**Comment by huan** [comment]
In additional: 

Since we are already using the `Babel` to transpile our code, change it to TypeScript will be very smooth, only need a little work, and then we can get all the benefits from the TypeDefs.

**Comment by julien-f** [comment]
I'm not opposed to a PR with TS code :stuck_out_tongue: 

But the compiled should be ES5.

**Comment by huan** [comment]
Awesome. I'll try to make a PR with TS code with a `tsconfig.json` to ES5 target.

Thank you for the acceptance! :smile:

**Comment by julien-f** [comment]
It would be nice if could generate Flow types from TS as well, do you not if that's possible?

**Comment by huan** [comment]
I had been never used Flow before, but I feel it should be possible to generate Flow Type Def from TS. Will search for it after I finished the TS PR.

**Comment by julien-f** [comment]
Yep, that's not a priority, it was just a question :slightly_smiling_face:

**Comment by huan** [comment]
Hi Julien, the PR had been submitted, please have a look at it and let me know what you think.

Hope we can enable the typing system soon!

**Comment by huan** [comment]
Hello, have you had time to review my PR?

Please let me know what you think about it, thanks.

**Comment by julien-f** [comment]
Released as 0.12.

**Comment by huan** [comment]
Awesome!
